import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://qlxjbwuaxgbdooyupvnx.supabase.co'
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFseGpid3VheGdiZG9veXVwdm54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MjQ0MjksImV4cCI6MjA5MTIwMDQyOX0.BJ0o_dcq1128dhzv1eKhaG7UWvxUpfmfc45loGfWZHM'

const supabase = createClient(supabaseUrl, supabaseKey)

async function insertBatch9() {
  const content = [
    {
      module_num: 1,
      section_title: 'KEGIATAN BELAJAR 4: Jenis-Jenis Layanan Bimbingan dan Konseling',
      sub_title: 'Layanan Bimbingan',
      content_type: 'materi',
      page_num: 32,
      body_text: `KEGIATAN BELAJAR 4: Jenis-Jenis Layanan Bimbingan dan Konseling\n\nA. LAYANAN ORIENTASI\n\nLayanan orientasi merupakan sebuah layanan konseling guna membantu konseli dalam memahami lingkungan barunya. Hal ini dilakukan untuk menunjang mereka dalam berperan aktif dan beradaptasi pada lingkungan baru tersebut (Prayitno, 2015). Lebih lanjut Prayitno menggambarkan bahwa layanan orientasi merupakan upaya bimbingan yang dilakukan untuk memperkenalkan peserta didik baru maupun individu lainnya kepada lingkungan baru yang akan mereka hadapi. Sedangkan menurut Sukardi (2008), layanan orientasi merupakan layanan bimbingan dan konseling yang dilakukan untuk membantu peserta ddidik dan orang tua memahami lingkungan baru, yakni lingkungan sekolah. Hal ini bertujuan untuk mempermudah sekaligus memastikan bahwa peran peserta didik pada lingkungan tersebut berjalan lancar.\n\nSecara keseluruhan, tujuan layanan orientasi adalah untuk mengakomodasi setiap individu agar dapat beradaptasi dengan lingkungan dan situasi baru. Dengan hadirnya layanan ini, setiap individu diharapkan mampu memaksimalkan dan mengambil manfaat dari segala sumber yang ada di lingkungan baru tersebut (Tohirin, 2013). Apabila ditinjau dari fungsi pemahaman, layanan ini mencoba untuk menunjang individu memahami aspek-aspek penting dari lingkungan baru yang akan dihadapi. Informasi baru tersebut kemudian dapat diproses dan digunakan untuk kepentingan yang bermanfaat. Kemudian dari fungsi pencegahan, layanan ini berguna untuk mencegah individu dari dampak negatif yang mungkin terjadi bila tidak mengetahui lingkungan barunya. Selanjutnya dari sudut pandang pengembangan, jika setiap individu mampu melihat, beradaptasi, serta memaksimalkan sumber yang tersedia pada lingkungan baru secara konstruktif, maka proses perkembangan dirinya akan jauh lebih baik.\n\nDalam prosesnya, layanan orientasi memiliki beberapa topik yang harus diberikan kepada peserta didik. Topik-topik yang dapat dibahas beragam, antara lain, sebagai berikut.\n1. Pengenalan umum terhadap sekolah.\n2. Pengenalan terhadap kelas dan semester baru.\n3. Pengenalan terhadap kelas, semester akhir, Ujian Akhir Sekolah, serta proses penerbitan ijazah.`
    },
    {
      module_num: 1,
      section_title: 'B. LAYANAN INFORMASI & C. LAYANAN PEMBELAJARAN',
      sub_title: 'Layanan Bimbingan',
      content_type: 'materi',
      page_num: 33,
      body_text: `B. LAYANAN INFORMASI\n\nLayanan informasi merupakan sebuah layanan konseling yang mencoba memberikan kesempatan bagi konseli untuk membuat keputusan yang berkaitan dengan kepentingan pribadinya bersumber dari beberapa informasi yang diterima. Layanan ini bertujuan untuk memberikan informasi yang diperlukan oleh individu sehingga mereka dapat dengan lebih mudah merencanakan dan mengambil keputusan yang tepat (Nurihsan, 2006).\n\nGunawan (1987) mendeskripsikan bahwa layanan informasi adalah upaya konseling yang mencoba memberikan kesempatan untuk peserta didik dalam membuat keputusan secara bijak dan mandiri. Untuk menghasilkan berbagai keputusan penting dalam kehidupan mereka, informasi yang disediakan harus dapat dipercaya. Lebih lanjut, layanan ini merupakan sebuah layanan guna mengatasi ketimpangan pemahaman dalam individu dengan menghadirkan informasi yang dibutuhkan (Tohirin, 2013). Pada layanan ini pun, berusaha memaknai lebih dalam proses perkembangan remaja dan lingkungan dengan menyampaikan pengetahuan serta pemahaman kepada peserta didik.\n\nDari berbagai pengertian yang telah disampaikan sebelumnya, dapat diungkapkan kembali bahwa layanan informasi merupakan layanan turunan dari kegiatan bimbingan dan konseling. Layanan ini bertujuan untuk memberikan informasi yang beragam, termasuk informasi tentang kehidupan pribadi, sosial, karier, dan pendidikan. Melalui pemberian informasi ini, diharapkan peserta didik dapat menyelesaikan masalah yang meraka hadapi secara menyeluruh. Selain daripada itu, layanan ini pun membantu meningkatkan pemahaman peserta didik tentang konsep diri serta membantu membimbing mereka dalam merencanakan masa depan dengan lebih baik.\n\nC. LAYANAN PEMBELAJARAN\n\nLayanan pembelajaran adalah jenis bimbingan untuk memahami materi maupun mencapai standar kompetensi peserta didik dengan kecepatan dan kemampuan mereka sendiri melalui pengembangan sikap dan kebiasaan belajar yang positif. Tujuan utama dari layanan pembelajaran adalah sebagai sarana proses pengembangan sikap serta kebiasaan belajar yang efektif. Layanan ini berfokus pada pengembangan.\n\nMenurut Yusuf & Nurihsan (2005), bimbingan belajar adalah jenis bimbingan yang membantu individu dalam mengatasi sekaligus menyelesaikan berbagai masalah akademik dengan membangun suasana belajar yang kondusif, hal ini diharapkan dapat membantu mengentaskan kesulitan dalam belajar. Setiap pembimbing bertanggung jawab untuk membantu menyelesaikan hambatan belajar, membuat metode belajar yang efektif, dan membantu mereka mencapai kesuksesan akademik. Dalam konteks bimbingan belajar, tujuan utamanya yakni membantu individu dalam mencapai tujuan akademik yang diharapkan.`
    },
    {
      module_num: 1,
      section_title: 'D. LAYANAN PENEMPATAN DAN PENYALURAN',
      sub_title: 'Layanan Bimbingan',
      content_type: 'materi',
      page_num: 34,
      body_text: `Berdasarkan beberapa pandangan tentang layanan bimbingan belajar di atas, dapat diungkapkan kembali bahwa layanan ini merupakan sebuah serangkaian layanan untuk membantu peserta didik dalam mengatasi masalah yang muncul pada akademiknya selama proses pembelajaran. Hal ini dilakukan melalui proses penciptaan lingkungan belajar yang berorientasi pada peserta didik untuk menghindari kesulitan dalam pembelajaran dan mencapai tingkat keberhasilan yang optimal sesuai dengan perkembangan pengetahuan, teknologi, dan seni, sehingga mereka siap untuk melanjutkan ke tingkat pendidikan yang lebih tinggi.\n\nDengan memberikan dorongan untuk terus belajar sepanjang hidup, layanan bimbingan belajar membantu peserta didik mencapai tingkat keberhasilan dalam proses pembelajaran dan mengoptimalkan pengembangan seluruh potensi mereka. Layanan ini mencapai tujuan ini dengan mendorong peserta didik untuk membuat kebiasaan belajar yang positif dan efektif yang sesuai dengan kemampuan, minat, dan peluang mereka. Tujuan ini sejalan dengan rencana pendidikan, yang bertujuan untuk mempersiapkan peserta didik secara mental untuk belajar sendiri (Nasution & Abdillah, 2019).\n\nD. LAYANAN PENEMPATAN DAN PENYALURAN\n\nLayanan konseling yang dikenal sebagai penempatan dan penyaluran memungkinkan konseli mendapatkan penempatan dan penyaluran yang sesuai dengan bakat dan kemampuan masing-masing individu. Menurut Tohirin (2013), layanan penempatan adalah layanan yang berupaya menunjang peserta didik dalam menyongsong masa depan mereka saat sedangan menempuh pendidikan maupun setelah menyelesaikan pendidikan, termasuk memilih pendidikan lanjutan sebagai bekal dalam mempersiapkan masa depan. Sementara menurut Prayitno (2004), layanan penempatan merupakan layanan yang bertujuan untuk mengatasi masalah ketidaksesuaian antara potensi yang dimiliki dalam individu maupun kelompok, serta membantu menempatkan pada lingkungan yang sesuai dengan memberi kesempatan untuk berkembang secara optimal.\n\nLayanan penempatan dan penyaluran bertujuan untuk membantu peserta didik menemukan lingkungan yang mereka butuhkan untuk mencapai potensi terbaik mereka. Lingkungan fisik, mental, sosial, dan budaya ini memengaruhi kehidupan dan perkembangan peserta didik. Layanan penempatan dan penyaluran juga bertujuan untuk menghindari ketidaksesuaian antara bakat individu dan upaya pengembangan mereka. Setiap peserta didik memiliki bakat dan potensi yang berbeda. Kadang-kadang, siswa tidak menyadari bakat mereka sepenuhnya. Diharapkan dengan hadirnya layanan ini akan membantu peserta didik untuk membuat keputusan yang sesuai dengan keahlian atau bakat mereka dalam merencanakan masa depan yang lebih baik (Nasution & Abdillah, 2019).`
    },
    {
      module_num: 1,
      section_title: 'E. LAYANAN PENGUASAAN KONTEN & F. LAYANAN KONSELING INDIVIDUAL',
      sub_title: 'Layanan Bimbingan',
      content_type: 'materi',
      page_num: 35,
      body_text: `E. LAYANAN PENGUASAAN KONTEN\n\nLayanan penguasaan konten merupakan bentuk layanan yang digunakan konseli untuk membantu meningkatkan kemampuan diri melalui pola belajar yang efektif, memperoleh materi pembelajaran yang disesuaikan dengan kecepatan dan tingkat kesulitan belajarnya. Menurut Prayitno (2015), layanan penguasaan konten (PKO) ini adalah sebuah rangkaian bantuan kepada individu maupun kelompok untuk mencapai sekaligus menguasai kompetensi tertentu setelah melalui proses pembelajaran.\n\nKemampuan atau kompetensi yang dipelajari dalam layanan ini merupakan satu unit konten yang mencakup berbagai elemen seperti fakta, data, konsep, proses, hukum, aturan, nilai, persepsi, afeksi, sikap, dan tindakan yang terkait. Dengan memperoleh penguasaan konten tersebut, diharapkan individu mampu memenuhi kebutuhan mereka dan mengatasi berbagai masalah yang mereka alami.\n\nLayanan penguasaan konten membantu peserta didik, baik secara individu maupun dalam kelompok, memperoleh keterampilan tertentu selama proses belajar. Layanan ini mengajarkan berbagai aspek, termasuk fakta, konsep, proses, hukum, nilai, persepsi, afeksi, sikap, dan tindakan. Dengan menguasai konten tersebut, diharapkan peserta didik dapat memenuhi kebutuhan dan menyelesaikan berbagai masalah. Penguasaan konten menjadi salah satu tujuan bimbingan konseling karena sangat penting bagi perkembangan peserta didik. Tujuan layanan penguasaan konten dapat dibagi menjadi dua kategori. Tujuan yang pertama melibatkan penguasaan suatu konten khusus, yang merupakan materi utama yang dikembangkan oleh guru pembimbing dan dipelajari oleh peserta didik. Sedangkan tujuan yang kedua melibatkan penguasaan suatu konten khusus (Nasution & Abdillah, 2019).\n\nF. LAYANAN KONSELING INDIVIDUAL\n\nHellen (2005) menjelaskan bahwa konseling individual merupakan jenis layanan bimbingan dan konseling di mana subjek konselingnya baik itu peserta didik ataupun konseli melakukan proses interaksi secara langsung untuk membahas proses sekaligus cara menyelesaikan masalah pribadi mereka. Konseling individual juga didefinisikan oleh Prayitno dan Erman Amti (2015) sebagai proses memberikan bantuan melalui wawancara konseling oleh seorang profesional (konselor) kepada individu yang mengalami masalah (konseli) dengan tujuan untuk memecahkan masalah yang sedang dihadapi oleh konseli.\n\nKonseling dianggap sebagai bagian penting dari proses pelayanan bimbingan secara keseluruhan. Hal ini menunjukkan bahwa disaat layanan konseling memberikan bantuan dengan baik, masalah yang dihadapi oleh konseli pun akan teratasi dengan baik, oleh karena itu, prosedur bimbingan lainnya dapat mengikuti sesuai dengan porsinya masing-masing. Selain itu, makna dari gagasan "jantung hati" adalah bahwa ketika seorang konselor memahami sepenuhnya apa, mengapa, dan bagaimana konseling bekerja, esensi dan keberhasilan proses itu sendiri akan meningkat.`
    }
  ];

  try {
    const { data, error } = await supabase.from('module_content').insert(content);
    if (error) throw error;
    console.log('Successfully inserted batch 9 (Pages 32-35)');
  } catch (err) {
    console.error('Error in batch 9:', err);
  }
}

insertBatch9();
